branches:  
  only:
    - master
    - /feature\/.+/
shallow_clone: true 
build_script:  
  - ps: .\build.ps1 -publish
artifacts:  
  - path: .\artefacts\*.zip
assembly_info:
  patch: false
test: off
deploy:  
  - provider: GitHub
    release: v$(release_version)
    auth_token:
      secure: AmCNluoUjQddLCZrNghd0XjLwFhrofDMF7UTdmJDLuK5g/+FKGfBr6IOIbN3hrRw
    artifact: .\*.zip
    draft: false
    prerelease: false
    on:
      branch: master